# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOjBM7gazSGTBgnJwxfWtv_n-DpClprY
"""

from google.colab import drive
drive.mount('/content/drive')

import torch

print("CUDA Available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

!pip install -q diffusers transformers accelerate safetensors
!pip install -q albumentations opencv-python pillow

import os
import csv
import random
import shutil
import sys

import cv2
import numpy as np

import torch

from PIL import Image

from diffusers import StableDiffusionImg2ImgPipeline

import albumentations as A

import csv
import os
import random

import torch
from PIL import Image
from diffusers import StableDiffusionImg2ImgPipeline
from google.colab import drive

drive.mount('/content/drive')

MODEL_PATH = "stable-diffusion-v1-5/stable-diffusion-v1-5"
INPUT_IMAGE = "/content/drive/MyDrive/CS402M/teammate1.jpeg"
OUTPUT_DIR = "/content/drive/MyDrive/CS402M/synthetic/class_B/B"

COUNT = 500
STRENGTH = 0.20

AGES = [
    "young adult appearance",
    "slightly younger adult appearance",
    "current age appearance",
    "slightly older adult appearance",
    "middle-aged appearance",
    "older adult appearance",
]

BUILDS = [
    "slender natural build",
    "average natural build",
    "slightly broader build",
    "slightly heavier natural build",
]

SCALES = [
    "close-up portrait framing",
    "medium portrait framing",
    "farther portrait framing",
    "head and shoulders framing",
]

LIGHTING = [
    "natural morning daylight",
    "soft afternoon daylight",
    "bright indoor lighting",
    "warm indoor lighting",
    "cool indoor lighting",
    "soft window lighting",
    "dim indoor lighting",
    "overcast outdoor lighting",
]

POSES = [
    "front-facing pose",
    "slightly turned to the left",
    "slightly turned to the right",
    "slightly looking upward",
    "slightly looking downward",
    "mild three-quarter view",
]

BACKGROUNDS = [
    "plain indoor wall",
    "subtle office background",
    "classroom background",
    "library background",
    "corridor background",
    "softly blurred indoor background",
    "natural outdoor background",
]

EXPRESSIONS = [
    "neutral relaxed expression",
    "subtle natural smile",
    "calm expression",
    "slightly serious expression",
    "gentle warm expression",
    "thoughtful expression",
]

CAMERA_STYLES = [
    "shot on DSLR camera",
    "shot on smartphone camera",
    "shot on mirrorless camera",
    "candid photography style",
    "studio photography style",
    "casual snapshot style",
]

CLOTHING = [
    "wearing a plain t-shirt",
    "wearing a collared shirt",
    "wearing a casual jacket",
    "wearing a hoodie",
    "wearing a formal shirt",
]

PROMPT_TEMPLATES = [
    "photorealistic portrait photograph of the same person, {age}, {build}, {scale}, {lighting}, {pose}, {background}, {expression}, {camera}, {clothing}, realistic facial features, natural skin texture, realistic photography, high quality",
    "a high quality photo of the same person, {clothing}, {expression}, {pose}, {scale}, {lighting}, set against {background}, {camera}, {age}, {build}, natural skin texture, sharp focus",
    "realistic {camera} photo of the same individual, {age}, {build}, {expression}, {pose}, {scale}, {background}, {lighting}, {clothing}, lifelike detail, high resolution",
]

NEGATIVE_PROMPT = (
    "different person, another person, multiple people, "
    "deformed face, distorted face, malformed eyes, malformed mouth, "
    "extra face, duplicate person, asymmetrical face, "
    "blurry face, cartoon, illustration, painting, "
    "unrealistic skin, extreme pose, extreme aging, low quality"
)

device = "cuda"

pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.float16,
)

pipe = pipe.to(device)
pipe.enable_attention_slicing()

os.makedirs(OUTPUT_DIR, exist_ok=True)

base_image = Image.open(INPUT_IMAGE).convert("RGB")

metadata_path = os.path.join(OUTPUT_DIR, "metadata.csv")

with open(metadata_path, "w", newline="") as f:
    writer = csv.writer(f)

    writer.writerow([
        "image",
        "identity",
        "age",
        "build",
        "scale",
        "lighting",
        "pose",
        "background",
        "expression",
        "camera",
        "clothing",
        "seed",
    ])

    for i in range(COUNT):

        age = random.choice(AGES)
        build = random.choice(BUILDS)
        scale = random.choice(SCALES)
        lighting = random.choice(LIGHTING)
        pose = random.choice(POSES)
        background = random.choice(BACKGROUNDS)
        expression = random.choice(EXPRESSIONS)
        camera = random.choice(CAMERA_STYLES)
        clothing = random.choice(CLOTHING)

        template = random.choice(PROMPT_TEMPLATES)
        prompt = template.format(
            age=age,
            build=build,
            scale=scale,
            lighting=lighting,
            pose=pose,
            background=background,
            expression=expression,
            camera=camera,
            clothing=clothing,
        )

        seed = random.randint(0, 2**32 - 1)

        generator = torch.Generator(device=device).manual_seed(seed)

        result = pipe(
            prompt=prompt,
            negative_prompt=NEGATIVE_PROMPT,
            image=input_image,
            strength=STRENGTH,
            guidance_scale=7.0,
            num_inference_steps=30,
            generator=generator,
        ).images[0]

        filename = f"B_{i + 1:04d}.png"
        filepath = os.path.join(OUTPUT_DIR, filename)

        result.save(filepath)

        writer.writerow([
            filename,
            "B",
            age,
            build,
            scale,
            lighting,
            pose,
            background,
            expression,
            camera,
            clothing,
            seed,
        ])

        print(f"Generated {i + 1}/{COUNT}: {filename}")

print("Class B generation complete.")

import csv
import os
import random

import torch
from PIL import Image, ImageEnhance
from diffusers import StableDiffusionImg2ImgPipeline
from google.colab import drive

drive.mount('/content/drive')

MODEL_PATH = "stable-diffusion-v1-5/stable-diffusion-v1-5"
INPUT_IMAGE = "/content/drive/MyDrive/CS402M/teammate1.jpeg"
OUTPUT_DIR = "/content/drive/MyDrive/CS402M/synthetic/class_A/A1"
IDENTITY_LABEL = "A1"
FILENAME_PREFIX = "A1"

COUNT = 500
STRENGTH = 0.20
AUGMENT_PROB = 0.25

AGES = [
    "young adult appearance",
    "slightly younger adult appearance",
    "current age appearance",
    "slightly older adult appearance",
    "middle-aged appearance",
    "older adult appearance",
]

BUILDS = [
    "slender natural build",
    "average natural build",
    "slightly broader build",
    "slightly heavier natural build",
]

SCALES = [
    "close-up portrait framing",
    "medium portrait framing",
    "farther portrait framing",
    "head and shoulders framing",
]

LIGHTING = [
    "natural morning daylight",
    "soft afternoon daylight",
    "bright indoor lighting",
    "warm indoor lighting",
    "cool indoor lighting",
    "soft window lighting",
    "dim indoor lighting",
    "overcast outdoor lighting",
]

POSES = [
    "front-facing pose",
    "slightly turned to the left",
    "slightly turned to the right",
    "slightly looking upward",
    "slightly looking downward",
    "mild three-quarter view",
]

BACKGROUNDS = [
    "plain indoor wall",
    "subtle office background",
    "classroom background",
    "library background",
    "corridor background",
    "softly blurred indoor background",
    "natural outdoor background",
]

EXPRESSIONS = [
    "neutral relaxed expression",
    "subtle natural smile",
    "calm expression",
    "slightly serious expression",
    "gentle warm expression",
    "thoughtful expression",
]

CAMERA_STYLES = [
    "shot on DSLR camera",
    "shot on smartphone camera",
    "shot on mirrorless camera",
    "candid photography style",
    "studio photography style",
    "casual snapshot style",
]

CLOTHING = [
    "wearing a plain t-shirt",
    "wearing a collared shirt",
    "wearing a casual jacket",
    "wearing a hoodie",
    "wearing a formal shirt",
]

PROMPT_TEMPLATES = [
    "photorealistic portrait photograph of the same person, {age}, {build}, {scale}, {lighting}, {pose}, {background}, {expression}, {camera}, {clothing}, realistic facial features, natural skin texture, realistic photography, high quality",
    "a high quality photo of the same person, {clothing}, {expression}, {pose}, {scale}, {lighting}, set against {background}, {camera}, {age}, {build}, natural skin texture, sharp focus",
    "realistic {camera} photo of the same individual, {age}, {build}, {expression}, {pose}, {scale}, {background}, {lighting}, {clothing}, lifelike detail, high resolution",
]

NEGATIVE_PROMPT = (
    "different person, another person, multiple people, "
    "deformed face, distorted face, malformed eyes, malformed mouth, "
    "extra face, duplicate person, asymmetrical face, "
    "blurry face, cartoon, illustration, painting, "
    "unrealistic skin, extreme pose, extreme aging, low quality"
)

def augment_image(image):
    """Conventional augmentation: horizontal flip, brightness jitter, rotation up to +-15deg."""
    aug_transforms = transforms.Compose([
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.ColorJitter(brightness=0.2),
        transforms.RandomRotation(degrees=15, fill=0),
    ])
    return aug_transforms(image)


def apply_augmentation(image):
    """Apply light conventional augmentation: flip, brightness jitter, rotation."""
    aug_applied = []

    if random.random() < 0.5:
        image = image.transpose(Image.FLIP_LEFT_RIGHT)
        aug_applied.append("flip")

    if random.random() < 0.7:
        factor = random.uniform(0.85, 1.15)
        image = ImageEnhance.Brightness(image).enhance(factor)
        aug_applied.append(f"brightness({factor:.2f})")

    angle = random.uniform(-15, 15)
    image = image.rotate(angle, resample=Image.BICUBIC, expand=False, fillcolor=(128, 128, 128))
    aug_applied.append(f"rotate({angle:.1f})")

    return image, ";".join(aug_applied)


device = "cuda"

pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.float16,
)

pipe = pipe.to(device)
pipe.enable_attention_slicing()

os.makedirs(OUTPUT_DIR, exist_ok=True)

base_image = Image.open(INPUT_IMAGE).convert("RGB")

metadata_path = os.path.join(OUTPUT_DIR, "metadata.csv")

with open(metadata_path, "w", newline="") as f:
    writer = csv.writer(f)

    writer.writerow([
        "image",
        "identity",
        "age",
        "build",
        "scale",
        "lighting",
        "pose",
        "background",
        "expression",
        "camera",
        "clothing",
        "seed",
        "augmentation",
    ])

    for i in range(COUNT):

        age = random.choice(AGES)
        build = random.choice(BUILDS)
        scale = random.choice(SCALES)
        lighting = random.choice(LIGHTING)
        pose = random.choice(POSES)
        background = random.choice(BACKGROUNDS)
        expression = random.choice(EXPRESSIONS)
        camera = random.choice(CAMERA_STYLES)
        clothing = random.choice(CLOTHING)

        template = random.choice(PROMPT_TEMPLATES)
        prompt = template.format(
            age=age,
            build=build,
            scale=scale,
            lighting=lighting,
            pose=pose,
            background=background,
            expression=expression,
            camera=camera,
            clothing=clothing,
        )

        seed = random.randint(0, 2**32 - 1)

        input_image = base_image.resize((512, 512))

        if random.random() < AUGMENT_PROB:
            input_image, aug_label = apply_augmentation(input_image)
        else:
            aug_label = "none"

        generator = torch.Generator(device=device).manual_seed(seed)

        result = pipe(
            prompt=prompt,
            negative_prompt=NEGATIVE_PROMPT,
            image=input_image,
            strength=STRENGTH,
            guidance_scale=7.0,
            num_inference_steps=30,
            generator=generator,
        ).images[0]

        filename = f"{FILENAME_PREFIX}_{i + 1:04d}.png"
        filepath = os.path.join(OUTPUT_DIR, filename)

        result.save(filepath)

        writer.writerow([
            filename,
            IDENTITY_LABEL,
            age,
            build,
            scale,
            lighting,
            pose,
            background,
            expression,
            camera,
            clothing,
            seed,
            aug_label,
        ])

        print(f"Generated {i + 1}/{COUNT}: {filename}")

print(f"Class {IDENTITY_LABEL} generation complete.")

import csv
import os
import random

import torch
from PIL import Image, ImageEnhance
from diffusers import StableDiffusionImg2ImgPipeline
from google.colab import drive

drive.mount('/content/drive')

MODEL_PATH = "stable-diffusion-v1-5/stable-diffusion-v1-5"
INPUT_IMAGE = "/content/drive/MyDrive/CS402M/teammate2.jpeg"
OUTPUT_DIR = "/content/drive/MyDrive/CS402M/synthetic/class_A/A2"
IDENTITY_LABEL = "A2"
FILENAME_PREFIX = "A2"

COUNT = 500
STRENGTH = 0.20
AUGMENT_PROB = 0.25

AGES = [
    "young adult appearance",
    "slightly younger adult appearance",
    "current age appearance",
    "slightly older adult appearance",
    "middle-aged appearance",
    "older adult appearance",
]

BUILDS = [
    "slender natural build",
    "average natural build",
    "slightly broader build",
    "slightly heavier natural build",
]

SCALES = [
    "close-up portrait framing",
    "medium portrait framing",
    "farther portrait framing",
    "head and shoulders framing",
]

LIGHTING = [
    "natural morning daylight",
    "soft afternoon daylight",
    "bright indoor lighting",
    "warm indoor lighting",
    "cool indoor lighting",
    "soft window lighting",
    "dim indoor lighting",
    "overcast outdoor lighting",
]

POSES = [
    "front-facing pose",
    "slightly turned to the left",
    "slightly turned to the right",
    "slightly looking upward",
    "slightly looking downward",
    "mild three-quarter view",
]

BACKGROUNDS = [
    "plain indoor wall",
    "subtle office background",
    "classroom background",
    "library background",
    "corridor background",
    "softly blurred indoor background",
    "natural outdoor background",
]

EXPRESSIONS = [
    "neutral relaxed expression",
    "subtle natural smile",
    "calm expression",
    "slightly serious expression",
    "gentle warm expression",
    "thoughtful expression",
]

CAMERA_STYLES = [
    "shot on DSLR camera",
    "shot on smartphone camera",
    "shot on mirrorless camera",
    "candid photography style",
    "studio photography style",
    "casual snapshot style",
]

CLOTHING = [
    "wearing a plain t-shirt",
    "wearing a collared shirt",
    "wearing a casual jacket",
    "wearing a hoodie",
    "wearing a formal shirt",
]

PROMPT_TEMPLATES = [
    "photorealistic portrait photograph of the same person, {age}, {build}, {scale}, {lighting}, {pose}, {background}, {expression}, {camera}, {clothing}, realistic facial features, natural skin texture, realistic photography, high quality",
    "a high quality photo of the same person, {clothing}, {expression}, {pose}, {scale}, {lighting}, set against {background}, {camera}, {age}, {build}, natural skin texture, sharp focus",
    "realistic {camera} photo of the same individual, {age}, {build}, {expression}, {pose}, {scale}, {background}, {lighting}, {clothing}, lifelike detail, high resolution",
]

NEGATIVE_PROMPT = (
    "different person, another person, multiple people, "
    "deformed face, distorted face, malformed eyes, malformed mouth, "
    "extra face, duplicate person, asymmetrical face, "
    "blurry face, cartoon, illustration, painting, "
    "unrealistic skin, extreme pose, extreme aging, low quality"
)

def augment_image(image):
    """Conventional augmentation: horizontal flip, brightness jitter, rotation up to +-15deg."""
    aug_transforms = transforms.Compose([
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.ColorJitter(brightness=0.2),
        transforms.RandomRotation(degrees=15, fill=0),
    ])
    return aug_transforms(image)


def apply_augmentation(image):
    """Apply light conventional augmentation: flip, brightness jitter, rotation."""
    aug_applied = []

    if random.random() < 0.5:
        image = image.transpose(Image.FLIP_LEFT_RIGHT)
        aug_applied.append("flip")

    if random.random() < 0.7:
        factor = random.uniform(0.85, 1.15)
        image = ImageEnhance.Brightness(image).enhance(factor)
        aug_applied.append(f"brightness({factor:.2f})")

    angle = random.uniform(-15, 15)
    image = image.rotate(angle, resample=Image.BICUBIC, expand=False, fillcolor=(128, 128, 128))
    aug_applied.append(f"rotate({angle:.1f})")

    return image, ";".join(aug_applied)


device = "cuda"

pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.float16,
)

pipe = pipe.to(device)
pipe.enable_attention_slicing()

os.makedirs(OUTPUT_DIR, exist_ok=True)

base_image = Image.open(INPUT_IMAGE).convert("RGB")

metadata_path = os.path.join(OUTPUT_DIR, "metadata.csv")

with open(metadata_path, "w", newline="") as f:
    writer = csv.writer(f)

    writer.writerow([
        "image",
        "identity",
        "age",
        "build",
        "scale",
        "lighting",
        "pose",
        "background",
        "expression",
        "camera",
        "clothing",
        "seed",
        "augmentation",
    ])

    for i in range(COUNT):

        age = random.choice(AGES)
        build = random.choice(BUILDS)
        scale = random.choice(SCALES)
        lighting = random.choice(LIGHTING)
        pose = random.choice(POSES)
        background = random.choice(BACKGROUNDS)
        expression = random.choice(EXPRESSIONS)
        camera = random.choice(CAMERA_STYLES)
        clothing = random.choice(CLOTHING)

        template = random.choice(PROMPT_TEMPLATES)
        prompt = template.format(
            age=age,
            build=build,
            scale=scale,
            lighting=lighting,
            pose=pose,
            background=background,
            expression=expression,
            camera=camera,
            clothing=clothing,
        )

        seed = random.randint(0, 2**32 - 1)

        input_image = base_image.resize((512, 512))

        if random.random() < AUGMENT_PROB:
            input_image, aug_label = apply_augmentation(input_image)
        else:
            aug_label = "none"

        generator = torch.Generator(device=device).manual_seed(seed)

        result = pipe(
            prompt=prompt,
            negative_prompt=NEGATIVE_PROMPT,
            image=input_image,
            strength=STRENGTH,
            guidance_scale=7.0,
            num_inference_steps=30,
            generator=generator,
        ).images[0]

        filename = f"{FILENAME_PREFIX}_{i + 1:04d}.png"
        filepath = os.path.join(OUTPUT_DIR, filename)

        result.save(filepath)

        writer.writerow([
            filename,
            IDENTITY_LABEL,
            age,
            build,
            scale,
            lighting,
            pose,
            background,
            expression,
            camera,
            clothing,
            seed,
            aug_label,
        ])

        print(f"Generated {i + 1}/{COUNT}: {filename}")

print(f"Class {IDENTITY_LABEL} generation complete.")

import os
import random
import shutil

# ==========================================
# INPUT FOLDER
# ==========================================
SOURCE_DIR = "/content/drive/MyDrive/CS402M/synthetic/class_B/B"

DEST_DIR = "/content/drive/MyDrive/CS402M/dataset/Class_B"

# ==========================================
# CREATE FOLDERS
# ==========================================

train_dir = os.path.join(DEST_DIR, "train")
val_dir = os.path.join(DEST_DIR, "val")
test_dir = os.path.join(DEST_DIR, "test")

os.makedirs(train_dir, exist_ok=True)
os.makedirs(val_dir, exist_ok=True)
os.makedirs(test_dir, exist_ok=True)

# ==========================================
# GET ALL IMAGES
# ==========================================

images = [
    f for f in os.listdir(SOURCE_DIR)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
]

print("Total Images:", len(images))

# Shuffle randomly
random.seed(42)
random.shuffle(images)

# ==========================================
# SPLIT
# ==========================================

train = images[:400]
val = images[400:450]
test = images[450:500]

# ==========================================
# COPY FILES
# ==========================================

for img in train:
    shutil.copy(
        os.path.join(SOURCE_DIR, img),
        os.path.join(train_dir, img)
    )

for img in val:
    shutil.copy(
        os.path.join(SOURCE_DIR, img),
        os.path.join(val_dir, img)
    )

for img in test:
    shutil.copy(
        os.path.join(SOURCE_DIR, img),
        os.path.join(test_dir, img)
    )

print("===================================")
print("Train :", len(train))
print("Validation :", len(val))
print("Test :", len(test))
print("Dataset split completed!")

import os

SOURCE_DIR = "/content/drive/MyDrive/CS402M/synthetic/class_B/B"

images = [
    f for f in os.listdir(SOURCE_DIR)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
]

print("Total images:", len(images))

