# -*- coding: utf-8 -*-
"""Training_CSS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gs0Au8mdwGtKgg_rTW0tcJe3Vy4ubamS
"""

import os

from google.colab import drive
drive.mount("/content/drive")

import tensorflow as tf
print(os.listdir('/content/drive/MyDrive'))
print("TensorFlow version:", tf.__version__)
print("Available GPUs:", tf.config.list_physical_devices("GPU"))

import random
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

SEED = 42
IMAGE_SIZE = 224
BATCH_SIZE = 32

random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

CLASS_NAMES = ["teammate1", "teammate2", "professor"]
CLASS_TO_IDX = {name: i for i, name in enumerate(CLASS_NAMES)}

# Change this only if your Drive folder is named differently.
# Point this at the "dataset" folder shown in your Drive screenshot.
DRIVE_ROOT = Path("/content/drive/MyDrive/CS402M-Face-Authentication/dataset")

# Identity subfolder -> class label (now a 1:1 mapping, no merging)
IDENTITY_TO_CLASS = {
    "Class_A/teammate1": "teammate1",
    "Class_A/teammate2": "teammate2",
    "Class_B/professor": "professor",
}

print("DRIVE_ROOT:", DRIVE_ROOT)
print("Exists?", DRIVE_ROOT.exists())

if DRIVE_ROOT.exists():
    print("\nContents of DRIVE_ROOT:")
    for p in sorted(DRIVE_ROOT.iterdir()):
        print(" ", repr(p.name))

    class_a = DRIVE_ROOT / "Class_A"
    if class_a.exists():
        print("\nContents of Class_A:")
        for p in sorted(class_a.iterdir()):
            print(" ", repr(p.name))

        teammate1 = class_a / "teammate1"
        if teammate1.exists():
            print("\nContents of Class_A/teammate1:")
            for p in sorted(teammate1.iterdir()):
                print(" ", repr(p.name))
        else:
            print("\nClass_A/teammate1 not found")
    else:
        print("\nClass_A not found under DRIVE_ROOT")
else:
    print("DRIVE_ROOT itself doesn't exist - check the exact Drive folder name and that Drive is mounted")

# Supports both possible layouts:
# CS402M-Face-Authentication/dataset/Class_A/teammate1/train
# CS402M-Face-Authentication/dataset/dataset/Class_A/teammate1/train

possible_dataset_roots = [
    DRIVE_ROOT,                  # .../CS402M-Face-Authentication/dataset
    DRIVE_ROOT / "dataset",      # in case of a nested duplicate folder
]

DATASET_ROOT = None

for possible_root in possible_dataset_roots:
    if (possible_root / "Class_A" / "teammate1" / "train").exists():
        DATASET_ROOT = possible_root
        break

assert DATASET_ROOT is not None, (
    "Dataset was not found. Check the Google Drive path. "
    "Expected: CS402M-Face-Authentication/dataset/Class_A/teammate1/train"
)

print("Using dataset folder:", DATASET_ROOT)

# Reverse lookup: class_name -> identity subfolder path
CLASS_TO_IDENTITY_PATH = {v: k for k, v in IDENTITY_TO_CLASS.items()}

def get_original_files(class_name, split_name):
    identity_path = CLASS_TO_IDENTITY_PATH[class_name]
    folder = DATASET_ROOT / identity_path / split_name

    assert folder.exists(), f"Missing folder: {folder}"

    # Ignore saved brightness/rotation/flip/noise copies.
    files = sorted(folder.glob("*_original_*.png"))

    if not files:
        # Fallback if your real files do not use "_original_" in their names.
        files = sorted(folder.glob("*.png"))

    return files


for split_name in ["train", "val", "test"]:
    print(f"\n{split_name.upper()}")

    for class_name in CLASS_NAMES:
        count = len(get_original_files(class_name, split_name))
        print(f"{class_name:10s}: {count} original images")

AUTOTUNE = tf.data.AUTOTUNE

def build_dataset(split_name, training=False):
    image_paths = []
    image_labels = []

    for label_index, class_name in enumerate(CLASS_NAMES):
        files = get_original_files(class_name, split_name)

        image_paths.extend([str(file) for file in files])
        image_labels.extend([label_index] * len(files))

    assert image_paths, f"No images found for {split_name}"

    dataset = tf.data.Dataset.from_tensor_slices((image_paths, image_labels))

    if training:
        dataset = dataset.shuffle(
            buffer_size=len(image_paths),
            seed=SEED,
            reshuffle_each_iteration=True,
        )

    def load_and_prepare_image(path, label):
        image_bytes = tf.io.read_file(path)
        image = tf.io.decode_jpeg(image_bytes, channels=3)

        # Keeps aspect ratio and avoids face distortion.
        image = tf.image.resize_with_pad(image, IMAGE_SIZE, IMAGE_SIZE)

        # MobileNetV3 expects RGB values in the normal 0–255 range.
        image = tf.cast(image, tf.float32)

        return image, label

    return (
        dataset
        .map(load_and_prepare_image, num_parallel_calls=AUTOTUNE)
        .batch(BATCH_SIZE)
        .prefetch(AUTOTUNE)
    )

train_ds = build_dataset("train", training=True)
val_ds = build_dataset("val", training=False)
test_ds = build_dataset("test", training=False)

print("Datasets created successfully.")

from IPython.display import display as show_image

images, labels = next(iter(train_ds))

plt.figure(figsize=(12, 9))

for index in range(min(12, len(images))):
    plt.subplot(3, 4, index + 1)
    plt.imshow(images[index].numpy().astype("uint8"))
    plt.title(CLASS_NAMES[int(labels[index])])
    plt.axis("off")

plt.tight_layout()
plt.show()

from tensorflow import keras
from tensorflow.keras import layers
import tensorflow as tf
data_augmentation = keras.Sequential(
    [
        layers.RandomFlip("horizontal", seed=SEED),
        layers.RandomRotation(0.10, fill_mode="reflect", seed=SEED),
        layers.RandomZoom(
            height_factor=(-0.10, 0.15),
            width_factor=(-0.10, 0.15),
            fill_mode="reflect",
            seed=SEED,
        ),
        layers.RandomContrast(0.15, seed=SEED),
        layers.RandomBrightness(
            factor=0.12,
            value_range=(0, 255),
            seed=SEED,
        ),
    ],
    name="data_augmentation",
)

# MobileNetV3Large already includes its required preprocessing.
# Do not add Rescaling(1/255) or mobilenet_v3.preprocess_input.
base_model = tf.keras.applications.MobileNetV3Large(
    input_shape=(IMAGE_SIZE, IMAGE_SIZE, 3),
    include_top=False,
    weights="imagenet",
    include_preprocessing=True,
)

base_model.trainable = False

inputs = keras.Input(
    shape=(IMAGE_SIZE, IMAGE_SIZE, 3),
    name="image",
)

x = data_augmentation(inputs)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D(name="global_average_pooling")(x)
x = layers.Dropout(0.40, seed=SEED)(x)

outputs = layers.Dense(
    len(CLASS_NAMES),
    activation="softmax",
    kernel_regularizer=keras.regularizers.l2(1e-4),
    name="classification",
)(x)

model = keras.Model(
    inputs=inputs,
    outputs=outputs,
    name="face_classifier",
)

model.compile(
    optimizer=keras.optimizers.AdamW(
        learning_rate=1e-3,
        weight_decay=1e-4,
    ),
    loss=keras.losses.SparseCategoricalCrossentropy(),
    metrics=[
        keras.metrics.SparseCategoricalAccuracy(name="accuracy"),
        keras.metrics.SparseTopKCategoricalAccuracy(
            k=2,
            name="top_2_accuracy",
        ),
    ],
)

model.summary()

MODEL_PATH = DRIVE_ROOT / "best_face_classifier.keras"

callbacks = [
    keras.callbacks.ModelCheckpoint(
        filepath=str(MODEL_PATH),
        monitor="val_accuracy",
        mode="max",
        save_best_only=True,
        verbose=1,
    ),
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=7,
        restore_best_weights=True,
        verbose=1,
    ),
    keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.3,
        patience=3,
        min_lr=1e-6,
        verbose=1,
    ),
]

history_head = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=30,
    callbacks=callbacks,
)

base_model.trainable = True

# Fine-tune only the last part of the pretrained model.
for layer in base_model.layers[:-35]:
    layer.trainable = False

model.compile(
    optimizer=keras.optimizers.AdamW(
        learning_rate=1e-5,
        weight_decay=1e-5,
    ),
    loss=keras.losses.SparseCategoricalCrossentropy(),
    metrics=[
        keras.metrics.SparseCategoricalAccuracy(name="accuracy"),
        keras.metrics.SparseTopKCategoricalAccuracy(
            k=2,
            name="top_2_accuracy",
        ),
    ],
)

history_fine = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    callbacks=callbacks,
)

# Restore the model with the best validation accuracy.
model = keras.models.load_model(str(MODEL_PATH))

test_loss, test_accuracy, test_top2_accuracy = model.evaluate(
    test_ds,
    verbose=1,
)

print(f"\nTest loss:           {test_loss:.4f}")
print(f"Test accuracy:       {test_accuracy * 100:.2f}%")
print(f"Test top-2 accuracy: {test_top2_accuracy * 100:.2f}%")

true_labels = np.concatenate(
    [labels.numpy() for _, labels in test_ds]
)

prediction_probabilities = model.predict(test_ds)
predicted_labels = np.argmax(prediction_probabilities, axis=1)

print(
    classification_report(
        true_labels,
        predicted_labels,
        target_names=CLASS_NAMES,
        digits=4,
    )
)

matrix = confusion_matrix(true_labels, predicted_labels)

confusion_display = ConfusionMatrixDisplay(
    confusion_matrix=matrix,
    display_labels=CLASS_NAMES,
)

fig, axis = plt.subplots(figsize=(7, 6))
confusion_display.plot(
    ax=axis,
    cmap="Blues",
    values_format="d",
)
plt.title("Test-set confusion matrix")
plt.show()

from google.colab import files
from PIL import Image
from IPython.display import display as show_image

uploaded = files.upload()

for uploaded_name in uploaded.keys():
    uploaded_image = Image.open(uploaded_name).convert("RGB")
    show_image(uploaded_image)

    # Same preprocessing as the training dataset.
    input_image = tf.convert_to_tensor(
        np.array(uploaded_image),
        dtype=tf.float32,
    )

    input_image = tf.image.resize_with_pad(
        input_image,
        IMAGE_SIZE,
        IMAGE_SIZE,
    )

    input_image = tf.expand_dims(input_image, axis=0)

    scores = model.predict(input_image, verbose=0)[0]

    best_index = int(np.argmax(scores))
    predicted_label = CLASS_NAMES[best_index]
    confidence = float(scores[best_index]) * 100

    # Derive the Drive folder (Class_A / Class_B) from IDENTITY_TO_CLASS,
    # e.g. "Class_A/teammate1" -> "Class_A"
    identity_path = CLASS_TO_IDENTITY_PATH[predicted_label]
    app_class = identity_path.split("/")[0]

    print(f"\nModel label:  {predicted_label}")
    print(f"Confidence:   {confidence:.2f}%")
    print(f"App class:    {app_class}")
    print("\nAll probabilities:")

    for class_name, score in zip(CLASS_NAMES, scores):
        print(f"  {class_name:10s}: {score * 100:.2f}%")

from google.colab import files
from PIL import Image
from IPython.display import display as show_image

uploaded = files.upload()

for uploaded_name in uploaded.keys():
    uploaded_image = Image.open(uploaded_name).convert("RGB")
    show_image(uploaded_image)

    # Same preprocessing as the training dataset.
    input_image = tf.convert_to_tensor(
        np.array(uploaded_image),
        dtype=tf.float32,
    )

    input_image = tf.image.resize_with_pad(
        input_image,
        IMAGE_SIZE,
        IMAGE_SIZE,
    )

    input_image = tf.expand_dims(input_image, axis=0)

    scores = model.predict(input_image, verbose=0)[0]

    best_index = int(np.argmax(scores))
    predicted_label = CLASS_NAMES[best_index]
    confidence = float(scores[best_index]) * 100

    # Derive the Drive folder (Class_A / Class_B) from IDENTITY_TO_CLASS,
    # e.g. "Class_A/teammate1" -> "Class_A"
    identity_path = CLASS_TO_IDENTITY_PATH[predicted_label]
    app_class = identity_path.split("/")[0]

    print(f"\nModel label:  {predicted_label}")
    print(f"Confidence:   {confidence:.2f}%")
    print(f"App class:    {app_class}")
    print("\nAll probabilities:")

    for class_name, score in zip(CLASS_NAMES, scores):
        print(f"  {class_name:10s}: {score * 100:.2f}%")

from google.colab import files
from PIL import Image
from IPython.display import display as show_image

uploaded = files.upload()

for uploaded_name in uploaded.keys():
    uploaded_image = Image.open(uploaded_name).convert("RGB")
    show_image(uploaded_image)

    # Same preprocessing as the training dataset.
    input_image = tf.convert_to_tensor(
        np.array(uploaded_image),
        dtype=tf.float32,
    )

    input_image = tf.image.resize_with_pad(
        input_image,
        IMAGE_SIZE,
        IMAGE_SIZE,
    )

    input_image = tf.expand_dims(input_image, axis=0)

    scores = model.predict(input_image, verbose=0)[0]

    best_index = int(np.argmax(scores))
    predicted_label = CLASS_NAMES[best_index]
    confidence = float(scores[best_index]) * 100

    # Derive the Drive folder (Class_A / Class_B) from IDENTITY_TO_CLASS,
    # e.g. "Class_A/teammate1" -> "Class_A"
    identity_path = CLASS_TO_IDENTITY_PATH[predicted_label]
    app_class = identity_path.split("/")[0]

    print(f"\nModel label:  {predicted_label}")
    print(f"Confidence:   {confidence:.2f}%")
    print(f"App class:    {app_class}")
    print("\nAll probabilities:")

    for class_name, score in zip(CLASS_NAMES, scores):
        print(f"  {class_name:10s}: {score * 100:.2f}%")

from google.colab import files
from PIL import Image
from IPython.display import display as show_image

uploaded = files.upload()

for uploaded_name in uploaded.keys():
    uploaded_image = Image.open(uploaded_name).convert("RGB")
    show_image(uploaded_image)

    # Same preprocessing as the training dataset.
    input_image = tf.convert_to_tensor(
        np.array(uploaded_image),
        dtype=tf.float32,
    )

    input_image = tf.image.resize_with_pad(
        input_image,
        IMAGE_SIZE,
        IMAGE_SIZE,
    )

    input_image = tf.expand_dims(input_image, axis=0)

    scores = model.predict(input_image, verbose=0)[0]

    best_index = int(np.argmax(scores))
    predicted_label = CLASS_NAMES[best_index]
    confidence = float(scores[best_index]) * 100

    # Derive the Drive folder (Class_A / Class_B) from IDENTITY_TO_CLASS,
    # e.g. "Class_A/teammate1" -> "Class_A"
    identity_path = CLASS_TO_IDENTITY_PATH[predicted_label]
    app_class = identity_path.split("/")[0]

    print(f"\nModel label:  {predicted_label}")
    print(f"Confidence:   {confidence:.2f}%")
    print(f"App class:    {app_class}")
    print("\nAll probabilities:")

    for class_name, score in zip(CLASS_NAMES, scores):
        print(f"  {class_name:10s}: {score * 100:.2f}%")

TFLITE_PATH = DRIVE_ROOT / "face_classifier_float32.tflite"
LABELS_PATH = DRIVE_ROOT / "face_classifier_labels.txt"

converter = tf.lite.TFLiteConverter.from_keras_model(model)

# Keep float32 input and output for Flutter compatibility.
converter.optimizations = []

tflite_model = converter.convert()

with open(TFLITE_PATH, "wb") as file:
    file.write(tflite_model)

with open(LABELS_PATH, "w") as file:
    file.write("\n".join(CLASS_NAMES))

print(f"Model saved:  {TFLITE_PATH}")
print(f"Labels saved: {LABELS_PATH}")
print(f"Model size:   {TFLITE_PATH.stat().st_size / (1024 * 1024):.2f} MB")

from google.colab import files

files.download(str(TFLITE_PATH))
files.download(str(LABELS_PATH))

print(TFLITE_PATH.exists(), TFLITE_PATH)
print(LABELS_PATH.exists(), LABELS_PATH)

# REPORT-VALUE GENERATOR
# Run this after model, train_ds, val_ds, test_ds, CLASS_NAMES,
# DATASET_ROOT, DRIVE_ROOT, IMAGE_SIZE, and BATCH_SIZE exist.

import os
import platform
import time
from pathlib import Path
from collections import Counter

import numpy as np
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix

print("=" * 70)
print("CS402M REPORT VALUES")
print("=" * 70)

# ------------------------------------------------------------
# 1. Environment and reproducibility values
# ------------------------------------------------------------
print("\n[1] ENVIRONMENT")
print("Python version:     ", platform.python_version())
print("TensorFlow version: ", tf.__version__)
print("GPU devices:        ", tf.config.list_physical_devices("GPU"))
print("Image size:         ", IMAGE_SIZE, "x", IMAGE_SIZE)
print("Batch size:         ", BATCH_SIZE)
print("Class order:        ", CLASS_NAMES)
print("Dataset root:       ", DATASET_ROOT)

# ------------------------------------------------------------
# 2. Dataset counts
# ------------------------------------------------------------
print("\n[2] DATASET COUNTS")

def original_files_for_report(class_name, split_name):
    # class_name is "teammate1" / "teammate2" / "professor";
    # map it back to its real subfolder, e.g. "Class_A/teammate1"
    identity_path = CLASS_TO_IDENTITY_PATH[class_name]
    folder = Path(DATASET_ROOT) / identity_path / split_name

    original_files = sorted(folder.glob("*_original_*.png"))

    if not original_files:
        original_files = sorted(folder.glob("*.png"))

    return original_files

dataset_total = 0

for split_name in ["train", "val", "test"]:
    split_total = 0
    print(f"\n{split_name.upper()}:")

    for class_name in CLASS_NAMES:
        count = len(original_files_for_report(class_name, split_name))
        split_total += count
        dataset_total += count
        print(f"  {class_name:12s}: {count}")

    print(f"  {'TOTAL':12s}: {split_total}")

print(f"\nTotal images used: {dataset_total}")

# ------------------------------------------------------------
# 3. Final validation and test metrics
# ------------------------------------------------------------
print("\n[3] MODEL METRICS")

val_results = model.evaluate(val_ds, verbose=0, return_dict=True)
test_results = model.evaluate(test_ds, verbose=0, return_dict=True)

print("\nValidation metrics:")
for metric_name, value in val_results.items():
    print(f"  {metric_name:25s}: {value:.6f} ({value * 100:.2f}% if accuracy)")

print("\nTest metrics:")
for metric_name, value in test_results.items():
    print(f"  {metric_name:25s}: {value:.6f} ({value * 100:.2f}% if accuracy)")

# ------------------------------------------------------------
# 4. Precision, recall, F1 score, and confusion matrix
# ------------------------------------------------------------
print("\n[4] CLASSIFICATION REPORT")

true_labels = np.concatenate([labels.numpy() for _, labels in test_ds])
prediction_probabilities = model.predict(test_ds, verbose=0)
predicted_labels = np.argmax(prediction_probabilities, axis=1)

report = classification_report(
    true_labels,
    predicted_labels,
    target_names=CLASS_NAMES,
    digits=4,
    output_dict=True,
)

print(
    classification_report(
        true_labels,
        predicted_labels,
        target_names=CLASS_NAMES,
        digits=4,
    )
)

matrix = confusion_matrix(true_labels, predicted_labels)

print("Confusion matrix:")
print(matrix)

print("\nPer-class report values:")
for class_name in CLASS_NAMES:
    values = report[class_name]
    print(
        f"  {class_name:12s} | "
        f"precision={values['precision'] * 100:.2f}% | "
        f"recall={values['recall'] * 100:.2f}% | "
        f"F1={values['f1-score'] * 100:.2f}% | "
        f"support={int(values['support'])}"
    )

# ------------------------------------------------------------
# 5. Model architecture and parameter count
# ------------------------------------------------------------
print("\n[5] MODEL DETAILS")
print("Model name:         ", model.name)
print("Total parameters:   ", f"{model.count_params():,}")

input_shape = model.input_shape
output_shape = model.output_shape

print("Input shape:        ", input_shape)
print("Output shape:       ", output_shape)

# ------------------------------------------------------------
# 6. TFLite file size
# ------------------------------------------------------------
print("\n[6] TFLITE DETAILS")

possible_tflite_paths = [
    Path(DRIVE_ROOT) / "face_classifier_float32.tflite",
    Path("/content") / "face_classifier_float32.tflite",
]

tflite_path = None

for possible_path in possible_tflite_paths:
    if possible_path.exists():
        tflite_path = possible_path
        break

if tflite_path is not None:
    file_size_mb = tflite_path.stat().st_size / (1024 * 1024)
    print("TFLite path:       ", tflite_path)
    print(f"TFLite size:        {file_size_mb:.2f} MB")
else:
    print("TFLite file not found. Run the TFLite export cell first.")

# ------------------------------------------------------------
# 7. Colab inference speed benchmark
# Note: this is Colab CPU/GPU speed, not emulator speed.
# ------------------------------------------------------------
print("\n[7] COLAB INFERENCE SPEED")

sample_images, _ = next(iter(test_ds))
sample_input = sample_images[:1]

# Warm-up inference
for _ in range(5):
    _ = model.predict(sample_input, verbose=0)

runs = 30
start_time = time.perf_counter()

for _ in range(runs):
    _ = model.predict(sample_input, verbose=0)

elapsed_seconds = time.perf_counter() - start_time
average_ms = (elapsed_seconds / runs) * 1000

print(f"Average Colab inference time: {average_ms:.2f} ms/image")
print("Use emulator timing separately in the report if required.")

# ------------------------------------------------------------
# 8. Ready-to-copy report summary
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("COPY THESE VALUES INTO THE REPORT")
print("=" * 70)

print(f"Dataset: {dataset_total} original images across {len(CLASS_NAMES)} identities")
print(f"Validation accuracy: {val_results.get('accuracy', 0) * 100:.2f}%")
print(f"Test accuracy: {test_results.get('accuracy', 0) * 100:.2f}%")

if "top_2_accuracy" in test_results:
    print(f"Top-2 accuracy: {test_results['top_2_accuracy'] * 100:.2f}%")

print(f"Test loss: {test_results.get('loss', 0):.4f}")
print(f"Parameters: {model.count_params():,}")

if tflite_path is not None:
    print(f"TFLite model size: {file_size_mb:.2f} MB")

print(f"Colab inference time: {average_ms:.2f} ms/image")
print("=" * 70)

import os

